"""RecoverAI synthetic data generator (v2). This is never merchant data."""
from __future__ import annotations
import argparse,json
from datetime import datetime,timezone
from pathlib import Path
import numpy as np
import pandas as pd
GENERATOR_VERSION='2.0'; DEFAULT_OUTPUT='ml/data/synthetic_payments_100k.csv'
FAILURES=['temporary_bank_error','insufficient_funds','card_declined','expired_card','authentication_failure','network_error','bank_unavailable','payment_method_error','customer_cancelled','unknown']; ACTIONS=['retry','reminder','alternative_payment_method','customer_notification','human_escalation','no_action']; VALID_STATUSES={'captured','failed'}
def sigmoid(x): return 1/(1+np.exp(-x))
def generate(rows=100000,seed=42):
 if rows<1: raise ValueError('rows must be positive')
 r=np.random.default_rng(seed); nc=max(2000,rows//10); ci=r.integers(0,nc,rows); age=r.integers(2,2200,nc); base=r.beta(12,3,nc); lifetime=r.lognormal(9,1,nc); prev=r.poisson(4+age/170,nc).clip(0,130); suc=np.array([r.binomial(int(n),p) for n,p in zip(prev,base)]); fail=prev-suc; segment=np.where((lifetime>np.quantile(lifetime,.88))&(base>.78),'high_value',np.where(base>.88,'loyal',np.where((age<80)|(prev<3),'new',np.where(base<.58,'at_risk','regular')))); cprev=prev[ci];cs=suc[ci];cf=fail[ci];sr=cs/np.maximum(cprev,1); cage=age[ci];clv=lifetime[ci]; seg=segment[ci]
 category=r.choice(['ecommerce','saas','education','healthcare','travel','food','retail','digital_services','professional_services'],rows,p=[.22,.16,.1,.08,.08,.11,.13,.07,.05]); method=r.choice(['card','upi','netbanking','wallet'],rows,p=[.4,.36,.14,.1]); created=pd.Timestamp('2024-01-01',tz='UTC')+pd.to_timedelta(r.integers(0,730*1440,rows),unit='m'); hour=created.hour.to_numpy();dow=created.dayofweek.to_numpy(); amount=np.clip(np.round(r.lognormal(7.45+np.where(seg=='high_value',.45,0),.82,rows)/10)*10,99,150000).astype(float); sub=r.choice(['active','past_due','cancelled','none'],rows,p=[.33,.1,.07,.5]);subage=np.where(sub=='none',0,r.integers(1,1500,rows));days=np.minimum(r.geometric(np.clip(.055+sr*.045,.02,.14))-1,365)
 fp=sigmoid(-2.5+.8*(1-sr)+.38*(sub=='past_due')+.22*(method=='card')+.16*(hour<6)+r.normal(0,.25,rows));failed=r.binomial(1,fp).astype(bool);reason=r.choice(FAILURES,rows,p=[.19,.19,.14,.09,.08,.12,.08,.05,.04,.02]);reason=np.where(failed,reason,None);status=np.where(failed,'failed','captured');retry=np.where(failed,np.minimum(r.poisson(.45+.7*(reason=='temporary_bank_error')+.35*(reason=='network_error'),rows),4),0); prior=np.minimum(r.binomial(np.minimum(cf,8),np.clip(.12+.52*sr,0,.85)),8);hist=np.where(cf>0,prior/np.maximum(cf,1),0.0);prev_action=r.choice(ACTIONS[:-1],rows,p=[.31,.24,.18,.14,.13]);prev_action=np.where(cf>0,prev_action,'no_action')
 temporary=np.isin(reason,['temporary_bank_error','network_error','bank_unavailable']); expcard=reason=='expired_card'; insufficient=reason=='insufficient_funds'; action=np.where(~failed,'no_action',np.where(temporary&(retry<2),'retry',np.where(expcard|((method=='card')&(reason=='payment_method_error')),'alternative_payment_method',np.where((amount>25000)|(seg=='high_value'),'human_escalation',np.where(insufficient,'reminder','customer_notification')))));action=np.where(failed&(sr<.35)&(retry>=2),'no_action',action)
 latent=-1.35+1.55*sr+.65*temporary+.33*hist-.48*retry+.18*(seg=='loyal')+.24*(seg=='high_value')-.55*(reason=='customer_cancelled')-.38*(reason=='card_declined')-.28*(sub=='cancelled')+.18*(action=='retry')+.13*(action=='alternative_payment_method')+.08*(action=='reminder')-.16*(action=='no_action')+r.normal(0,.70,rows);prob=np.clip(sigmoid(latent),.01,.96);recovered=np.where(failed,r.binomial(1,prob),0).astype(int);source=np.select([reason=='customer_cancelled',np.isin(reason,['temporary_bank_error','network_error','bank_unavailable'])],['customer','gateway'],default='issuer');step=np.select([reason=='authentication_failure',reason=='payment_method_error'],['authentication','payment_method'],default='authorization')
 return pd.DataFrame({'customer_id':['cus_'+str(x).zfill(6) for x in ci],'payment_id':['pay_'+str(x).zfill(8) for x in range(rows)],'order_id':['ord_'+str(x).zfill(8) for x in range(rows)],'merchant_id':['mer_'+str(x).zfill(3) for x in r.integers(1,301,rows)],'amount':amount,'currency':'INR','payment_method':method,'payment_status':status,'created_at':created.astype(str),'failure_reason':reason,'failure_code':reason,'failure_source':source,'failure_step':step,'customer_age_days':cage,'previous_payment_count':cprev,'previous_success_count':cs,'previous_failure_count':cf,'customer_success_rate':np.round(sr,4),'average_transaction_amount':np.round(np.maximum(99,amount*r.lognormal(0,.28,rows)),2),'customer_lifetime_value':np.round(clv,2),'days_since_last_payment':days,'retry_count':retry,'previous_recovery_count':prior,'historical_recovery_rate':np.round(hist,4),'previous_intervention':prev_action,'subscription_status':sub,'subscription_age_days':subage,'time_of_day':hour,'day_of_week':dow,'merchant_category':category,'customer_segment':seg,'recovery_action':action,'recovered':recovered,'recovered_amount':np.where(recovered,amount,0.0)})
def validate(df):
 problems=[]
 if df.payment_id.duplicated().any() or df.order_id.duplicated().any():problems.append('duplicate payment/order id')
 if (df.amount<=0).any() or (df.recovered_amount<0).any() or (df.recovered_amount>df.amount).any():problems.append('invalid amount')
 if not set(df.payment_status).issubset(VALID_STATUSES):problems.append('invalid status')
 if (df.retry_count<0).any() or (df.retry_count>4).any():problems.append('invalid retries')
 if not ((df.previous_success_count+df.previous_failure_count)==df.previous_payment_count).all():problems.append('inconsistent history')
 if not ((df.recovered==0)|(df.payment_status=='failed')).all():problems.append('captured payment marked recovered')
 return {'passed':not problems,'problems':problems,'null_counts':df.isna().sum().to_dict(),'rows':len(df)}
def summary(df):
 f=df[df.payment_status=='failed'];print('\nDataset generated successfully.');print(f'Rows: {len(df):,}\nSuccessful payments: {(df.payment_status=="captured").sum():,}\nFailed payments: {len(f):,}\nRecovery rate (failed only): {f.recovered.mean():.2%}\nTotal payment value: INR {df.amount.sum():,.0f}\nPotential recoverable value: INR {f.amount.sum():,.0f}')
 for c in ['failure_reason','payment_method','customer_segment','recovery_action']:print(f'\n{c} distribution:\n{df[c].value_counts(dropna=False).to_string()}')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--rows',type=int,default=100000);p.add_argument('--seed',type=int,default=42);p.add_argument('--output',default=DEFAULT_OUTPUT);a=p.parse_args();out=Path(a.output);out.parent.mkdir(parents=True,exist_ok=True);df=generate(a.rows,a.seed);check=validate(df)
 if not check['passed']:raise SystemExit(str(check))
 df.to_csv(out,index=False);out.with_suffix('.metadata.json').write_text(json.dumps({'generator_version':GENERATOR_VERSION,'seed':a.seed,'rows':a.rows,'generated_at':datetime.now(timezone.utc).isoformat(),'validation':check},indent=2));summary(df)
