import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Navigate, NavLink, Outlet, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, authApi, getData, TOKEN_KEY } from './services/api';
import './style.css';

type AnyRecord = Record<string, any>;
const money = (v: unknown) => typeof v === 'number' ? new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(v) : '—';
const pct = (v: unknown) => typeof v === 'number' ? `${(v * 100).toFixed(1)}%` : '—';
const date = (v: unknown) => v ? new Date(String(v)).toLocaleString() : '—';
const label = (v: unknown) => String(v ?? '—').replaceAll('_', ' ');
function State({ kind, children }: { kind: 'loading' | 'error' | 'empty'; children: React.ReactNode }) { return <div className={`state ${kind}`}>{children}</div>; }
function Badge({ value }: { value: unknown }) { const text = label(value); return <span className={`badge ${String(value ?? '').toLowerCase().replaceAll('_', '-')}`}>{text}</span>; }
function Metric({ title, value, hint }: { title: string; value: React.ReactNode; hint?: string }) { return <article className="metric"><small>{title}</small><strong>{value}</strong>{hint && <span>{hint}</span>}</article>; }
function ErrorState({ message = 'Unable to load data. Please try again.' }: { message?: string }) { return <State kind="error">{message}</State>; }

function LoginPage() {
  const nav = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const mutation = useMutation({ mutationFn: () => authApi.login({ email, password }), onSuccess: (r) => { localStorage.setItem(TOKEN_KEY, r.data.access_token); nav('/dashboard', { replace: true }); }, onError: (e: any) => setError(e.response?.data?.detail || 'Sign in failed. Check your credentials.') });
  if (localStorage.getItem(TOKEN_KEY)) return <Navigate to="/dashboard" replace />;
  return <main className="login-page"><div className="login-card"><div className="brand-mark">R</div><h1>RecoverAI</h1><p>Autonomous revenue recovery, made accountable.</p><form onSubmit={(e) => { e.preventDefault(); setError(''); mutation.mutate(); }}><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="email" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete="current-password" /></label>{error && <div className="form-error">{error}</div>}<button disabled={mutation.isPending}>{mutation.isPending ? 'Signing in…' : 'Sign in'}</button></form><small>Synthetic/demo records are clearly labelled in the workspace.</small></div></main>;
}
function ProtectedRoute() { return localStorage.getItem(TOKEN_KEY) ? <Outlet /> : <Navigate to="/login" replace />; }
function Shell() {
  const nav = useNavigate(); const loc = useLocation(); const me = useQuery({ queryKey: ['me'], queryFn: () => getData<AnyRecord>('/api/auth/me'), retry: false });
  const links = [['/dashboard', 'Dashboard'], ['/payments', 'Payments'], ['/recovery', 'Recovery'], ['/analytics', 'Analytics'], ['/agents', 'Agents'], ['/audit', 'Audit']];
  return <div className="app-shell"><aside className="sidebar"><Link to="/dashboard" className="logo"><span>R</span><div><b>RecoverAI</b><small>Revenue intelligence</small></div></Link><nav>{links.map(([to, text]) => <NavLink key={to} to={to} className={({ isActive }) => isActive ? 'active' : ''}>{text}</NavLink>)}</nav><div className="sidebar-bottom"><div className="user-chip"><span className="avatar">{String(me.data?.email || 'U').slice(0, 1).toUpperCase()}</span><div><b>{me.data?.email || 'Authenticated user'}</b><small>{me.data?.role || 'Operator'}</small></div></div><button className="ghost" onClick={() => { localStorage.removeItem(TOKEN_KEY); nav('/login', { replace: true }); }}>Log out</button></div></aside><main className="workspace"><header className="topbar"><div><small>RecoverAI / {loc.pathname.split('/')[1] || 'dashboard'}</small><h1>{links.find(([to]) => loc.pathname.startsWith(to))?.[1] || 'Dashboard'}</h1></div><span className="demo-pill">Synthetic data workspace</span></header><Outlet /></main></div>;
}
function DashboardPage() {
  const overview = useQuery({ queryKey: ['overview'], queryFn: () => getData<AnyRecord>('/api/analytics/overview'), refetchInterval: 15000 }); const opps = useQuery({ queryKey: ['opportunities'], queryFn: () => getData<AnyRecord[]>('/api/recovery/opportunities'), refetchInterval: 15000 });
  if (overview.isLoading || opps.isLoading) return <State kind="loading">Loading revenue intelligence…</State>; if (overview.isError) return <ErrorState />; const d = overview.data || {}; const list = opps.data || [];
  const pending = list.filter((x) => String(x.guardrail?.decision_status || x.state).toUpperCase() === 'HUMAN_REVIEW').length; const auto = list.filter((x) => String(x.guardrail?.decision_status || x.state).toUpperCase() === 'AUTO_APPROVED').length;
  return <><section className="hero"><div><p className="eyebrow">Detect · Decide · Recover</p><h2>Good morning, your recovery queue is ready.</h2><p>Prioritize revenue using model-backed decisions and deterministic guardrails.</p></div><Link className="button" to="/recovery">Review opportunities</Link></section><section className="metric-grid"><Metric title="Revenue at risk" value={money(d.revenue_at_risk)} /><Metric title="Expected recovery" value={money(d.recovery_opportunity)} /><Metric title="Recovered revenue" value={money(d.recovered_revenue)} /><Metric title="Recovery rate" value={pct(d.recovery_rate)} /><Metric title="Active actions" value={d.active_actions ?? '—'} /><Metric title="Human review" value={pending} hint="From current opportunities" /><Metric title="Auto-approved" value={auto} hint="From current opportunities" /></section><section className="panel"><div className="panel-heading"><div><h2>Highest-value opportunities</h2><p>Live records from the recovery API.</p></div><Link to="/recovery" className="text-link">View all →</Link></div><OpportunityTable rows={list.slice(0, 8)} /></section></>;
}
function OpportunityTable({ rows }: { rows: AnyRecord[] }) { if (!rows.length) return <State kind="empty">No recovery opportunities found.</State>; return <div className="table-wrap"><table><thead><tr><th>Payment</th><th>Customer</th><th>Amount</th><th>Probability</th><th>Expected recovery</th><th>Action</th><th>Priority</th><th>Status</th></tr></thead><tbody>{rows.map((x) => <tr key={x.id}><td><Link className="text-link" to={`/recovery/${x.id}`}>{x.payment_id}</Link></td><td>{x.customer_id || '—'}</td><td>{money(x.amount)}</td><td>{pct(x.probability)}</td><td>{money(x.expected_recovery_value)}</td><td>{label(x.recommended_action)}</td><td><Badge value={x.priority} /></td><td><Badge value={x.guardrail?.decision_status || x.state} /></td></tr>)}</tbody></table></div>; }
function PaymentsPage() { const q = useQuery({ queryKey: ['payments'], queryFn: () => getData<AnyRecord[]>('/api/payments') }); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const rows = useMemo(() => (q.data || []).filter((x) => `${x.payment_id} ${x.id} ${x.status} ${x.failure_reason || ''}`.toLowerCase().includes(search.toLowerCase()) && (status === 'all' || String(x.status).toLowerCase() === status)), [q.data, search, status]); return <section className="panel"><div className="panel-heading"><div><h2>Payment explorer</h2><p>Search payments and inspect their recovery assessment.</p></div></div><div className="filters"><input placeholder="Search payment, status or failure…" value={search} onChange={(e) => setSearch(e.target.value)} /><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All statuses</option><option value="failed">Failed</option><option value="captured">Captured</option><option value="authorized">Authorized</option></select></div>{q.isLoading ? <State kind="loading">Loading payments…</State> : q.isError ? <ErrorState /> : !rows.length ? <State kind="empty">No payments match these filters.</State> : <div className="table-wrap"><table><thead><tr><th>Payment ID</th><th>Amount</th><th>Method</th><th>Status</th><th>Failure reason</th><th>Created</th></tr></thead><tbody>{rows.map((x) => <tr key={x.payment_id || x.id}><td><Link className="text-link" to={`/payments/${x.payment_id || x.id}`}>{x.payment_id || x.id}</Link></td><td>{money(x.amount)}</td><td>{label(x.payment_method)}</td><td><Badge value={x.status} /></td><td>{label(x.failure_reason)}</td><td>{date(x.created_at)}</td></tr>)}</tbody></table></div>}</section>; }
function Assessment({ data, opportunity }: { data: AnyRecord; opportunity?: AnyRecord }) { const prediction = data.prediction || opportunity?.prediction || {}; const scores = data.intervention_scores || opportunity?.intervention_scores || {}; const ranked = Object.entries(scores).sort(([, a]: any, [, b]: any) => (b.expected_recovery_value ?? b.effectiveness ?? 0) - (a.expected_recovery_value ?? a.effectiveness ?? 0)); const guard = data.opportunity?.guardrail || opportunity?.guardrail || {}; return <><div className="detail-grid"><section className="panel"><h3>ML assessment</h3><div className="big-probability">{pct(prediction.probability)}</div><p>Recovery probability</p><dl><dt>Model version</dt><dd>{prediction.model_version || '—'}</dd><dt>Prediction source</dt><dd>{prediction.factors?.prediction_source || prediction.prediction_source || 'MODEL'}</dd><dt>Expected recovery</dt><dd>{money(data.opportunity?.expected_recovery_value || opportunity?.expected_recovery_value)}</dd><dt>Priority</dt><dd><Badge value={data.opportunity?.priority || opportunity?.priority} /></dd></dl></section><section className="panel"><h3>Decision & guardrails</h3><dl><dt>Recommended action</dt><dd>{label(data.opportunity?.action || opportunity?.recommended_action)}</dd><dt>Decision status</dt><dd><Badge value={guard.decision_status || data.opportunity?.state || opportunity?.state} /></dd><dt>Guardrail result</dt><dd>{guard.passed === false ? 'Blocked' : guard.reason || 'Backend result available'}</dd></dl>{guard.reasons && <ul className="reason-list">{(Array.isArray(guard.reasons) ? guard.reasons : [guard.reasons]).map((r: any) => <li key={String(r)}>{String(r)}</li>)}</ul>}</section></div><section className="panel"><div className="panel-heading"><div><h3>Intervention ranking</h3><p>Scores returned by the backend intervention service.</p></div></div>{ranked.length ? <div className="ranking">{ranked.map(([action, value]: any) => <div className="rank-row" key={action}><b>{label(action)}</b><span>{pct(value.effectiveness)}</span><strong>{money(value.expected_recovery_value)}</strong></div>)}</div> : <State kind="empty">No intervention scores are available.</State>}</section></>; }
function ActionControls({ opportunity }: { opportunity: AnyRecord }) { const qc = useQueryClient(); const [message, setMessage] = useState(''); const run = useMutation({ mutationFn: (kind: string) => api.post(`/api/recovery/${opportunity.id}/${kind}`), onSuccess: () => { setMessage('Action accepted by the backend.'); qc.invalidateQueries({ queryKey: ['opportunity', opportunity.id] }); qc.invalidateQueries({ queryKey: ['opportunities'] }); qc.invalidateQueries({ queryKey: ['overview'] }); }, onError: (e: any) => setMessage(e.response?.data?.detail || 'The backend rejected this action.') }); const state = String(opportunity.guardrail?.decision_status || opportunity.state || '').toUpperCase(); if (state === 'HUMAN_REVIEW') return <div className="action-box"><b>Human approval required</b><p>Review the server-side decision before execution.</p><button disabled={run.isPending} onClick={() => run.mutate('approve')}>Approve</button><button className="secondary" disabled={run.isPending} onClick={() => run.mutate('reject')}>Reject</button>{message && <small>{message}</small>}</div>; if (state === 'AUTO_APPROVED') return <div className="action-box"><b>Action permitted</b><p>The backend has approved this recovery. Execute only the recommended action.</p><button disabled={run.isPending} onClick={() => run.mutate('execute')}>{run.isPending ? 'Executing…' : 'Execute recovery'}</button>{message && <small>{message}</small>}</div>; return <div className="action-box muted"><b>No automatic execution available</b><p>{state === 'BLOCKED' ? 'Guardrails blocked this action.' : 'No action is recommended for this opportunity.'}</p></div>; }
function Timeline({ paymentId }: { paymentId?: string }) { const q = useQuery({ queryKey: ['activity'], queryFn: () => getData<AnyRecord[]>('/api/agents/activity') }); const rows = (q.data || []).filter((x) => !paymentId || x.payment_id === paymentId); if (q.isLoading) return <State kind="loading">Loading agent activity…</State>; if (q.isError) return <ErrorState />; if (!rows.length) return <State kind="empty">No agent activity recorded.</State>; return <div className="timeline">{rows.map((x, i) => <div className="timeline-item" key={`${x.timestamp}-${i}`}><span className="timeline-dot" /><div><b>{x.agent || 'System'}</b><small>{date(x.timestamp)}</small><p>{x.action || x.reason || 'Event recorded'}</p></div></div>)}</div>; }
function PaymentDetail({ opportunityMode = false }: { opportunityMode?: boolean }) { const params = useParams(); const id = params.paymentId || params.opportunityId || ''; const q = useQuery({ queryKey: [opportunityMode ? 'opportunity' : 'payment', id], queryFn: () => getData<AnyRecord>(opportunityMode ? `/api/recovery/opportunities/${id}` : `/api/payments/${id}`), enabled: Boolean(id) }); if (q.isLoading) return <State kind="loading">Loading details…</State>; if (q.isError || !q.data) return <ErrorState message="This record could not be loaded." />; const d = q.data; const opportunity = opportunityMode ? d : d.opportunity; return <><div className="detail-header"><div><p className="eyebrow">{opportunityMode ? 'Recovery opportunity' : 'Payment detail'}</p><h2>{d.payment_id || d.id}</h2><p>{opportunityMode ? `Payment ${d.payment_id}` : `${label(d.status)} · ${money(d.amount)}`}</p></div>{opportunity && <ActionControls opportunity={{ ...opportunity, id: opportunity.id || d.id }} />}</div>{!opportunityMode && <section className="panel"><h3>Payment information</h3><div className="facts"><div><small>Amount</small><b>{money(d.amount)}</b></div><div><small>Status</small><b><Badge value={d.status} /></b></div><div><small>Method</small><b>{label(d.payment_method)}</b></div><div><small>Failure reason</small><b>{label(d.failure_reason)}</b></div><div><small>Customer</small><b>{d.customer?.id || d.customer_id || '—'}</b></div><div><small>Customer success rate</small><b>{pct(d.customer?.success_rate)}</b></div></div></section>}<Assessment data={d} opportunity={opportunity} /><section className="panel"><h3>Agent timeline</h3><Timeline paymentId={d.payment_id} /></section></>; }
function RecoveryPage() { const q = useQuery({ queryKey: ['opportunities'], queryFn: () => getData<AnyRecord[]>('/api/recovery/opportunities') }); const [decision, setDecision] = useState('all'); const [priority, setPriority] = useState('all'); const rows = (q.data || []).filter((x) => (decision === 'all' || String(x.guardrail?.decision_status || x.state).toUpperCase() === decision) && (priority === 'all' || String(x.priority).toUpperCase() === priority)); return <section className="panel"><div className="panel-heading"><div><h2>Recovery opportunities</h2><p>Prioritized by expected recovery value and policy.</p></div></div><div className="filters"><select value={decision} onChange={(e) => setDecision(e.target.value)}><option value="all">All decisions</option><option>AUTO_APPROVED</option><option>HUMAN_REVIEW</option><option>NO_ACTION</option><option>BLOCKED</option></select><select value={priority} onChange={(e) => setPriority(e.target.value)}><option value="all">All priorities</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></div>{q.isLoading ? <State kind="loading">Loading opportunities…</State> : q.isError ? <ErrorState /> : <OpportunityTable rows={rows} />}</section>; }
function AnalyticsPage() { const overview = useQuery({ queryKey: ['overview'], queryFn: () => getData<AnyRecord>('/api/analytics/overview') }); const interventions = useQuery({ queryKey: ['interventions'], queryFn: () => getData<AnyRecord[]>('/api/analytics/interventions') }); if (overview.isLoading || interventions.isLoading) return <State kind="loading">Loading analytics…</State>; if (overview.isError || interventions.isError) return <ErrorState />; const d = overview.data || {}; return <><section className="metric-grid"><Metric title="Revenue at risk" value={money(d.revenue_at_risk)} /><Metric title="Expected recovery" value={money(d.recovery_opportunity)} /><Metric title="Recovered revenue" value={money(d.recovered_revenue)} /><Metric title="Recovery rate" value={pct(d.recovery_rate)} /></section><section className="panel"><h2>Intervention effectiveness</h2><p>Values are calculated by the backend from recorded outcomes.</p>{!(interventions.data || []).length ? <State kind="empty">No intervention outcome data is available.</State> : <div className="table-wrap"><table><thead><tr><th>Intervention</th><th>Attempts</th><th>Recovered revenue</th></tr></thead><tbody>{(interventions.data || []).map((x) => <tr key={x.action}><td>{label(x.action)}</td><td>{x.attempts ?? '—'}</td><td>{money(x.recovered_revenue)}</td></tr>)}</tbody></table></div>}</section></>; }
function AgentsPage() { const q = useQuery({ queryKey: ['activity'], queryFn: () => getData<AnyRecord[]>('/api/agents/activity') }); if (q.isLoading) return <State kind="loading">Loading agent activity…</State>; if (q.isError) return <ErrorState />; const rows = q.data || []; const counts = rows.reduce((m: AnyRecord, x) => { m[x.agent || 'System'] = (m[x.agent || 'System'] || 0) + 1; return m; }, {}); return <><section className="metric-grid">{['DetectionAgent', 'DiagnosisAgent', 'DecisionAgent', 'ExecutionAgent', 'OutcomeAgent'].map((a) => <Metric key={a} title={a.replace('Agent', ' agent')} value={counts[a] || 0} hint="Recorded events" />)}</section><section className="panel"><h2>Recent agent activity</h2><Timeline /></section></>; }
function AuditPage() { const q = useQuery({ queryKey: ['audit'], queryFn: () => getData<AnyRecord[]>('/api/audit-logs') }); if (q.isLoading) return <State kind="loading">Loading audit trail…</State>; if (q.isError) return <ErrorState />; const rows = q.data || []; return <section className="panel"><h2>Audit trail</h2><p>Safe operational events from the backend.</p>{!rows.length ? <State kind="empty">No audit events found.</State> : <div className="table-wrap"><table><thead><tr><th>Timestamp</th><th>Agent</th><th>Payment</th><th>Action</th><th>Reason</th><th>Metadata</th></tr></thead><tbody>{rows.map((x, i) => <tr key={`${x.timestamp}-${i}`}><td>{date(x.timestamp)}</td><td>{x.agent || '—'}</td><td>{x.payment_id || '—'}</td><td>{label(x.action)}</td><td>{x.reason || '—'}</td><td><code>{x.details ? JSON.stringify(x.details) : '—'}</code></td></tr>)}</tbody></table></div>}</section>; }
function App() { return <Routes><Route path="/login" element={<LoginPage />} /><Route element={<ProtectedRoute />}><Route element={<Shell />}><Route path="/" element={<Navigate to="/dashboard" replace />} /><Route path="/dashboard" element={<DashboardPage />} /><Route path="/payments" element={<PaymentsPage />} /><Route path="/payments/:paymentId" element={<PaymentDetail />} /><Route path="/recovery" element={<RecoveryPage />} /><Route path="/recovery/:opportunityId" element={<PaymentDetail opportunityMode />} /><Route path="/analytics" element={<AnalyticsPage />} /><Route path="/agents" element={<AgentsPage />} /><Route path="/audit" element={<AuditPage />} /></Route></Route><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={new QueryClient()}><BrowserRouter><App /></BrowserRouter></QueryClientProvider></React.StrictMode>);
